var area_code = [ 
{ "level": "ALL", "code": "ALL", "text": "全國" }, 
{ "level": "Air", "code": "1", "text": "二仁溪流域" } ,
{ "level": "Air", "code": "2", "text": "八掌溪流域" } ,
{ "level": "Air", "code": "3", "text": "三棧溪流域" } ,
{ "level": "Air", "code": "4", "text": "大甲溪流域" } ,
{ "level": "Air", "code": "5", "text": "大安溪流域" } ,
{ "level": "Air", "code": "6", "text": "中港溪流域" } ,
{ "level": "Air", "code": "7", "text": "太平溪流域" } ,
{ "level": "Air", "code": "8", "text": "冬山河流域" } ,
{ "level": "Air", "code": "9", "text": "北港溪流域" } ,
{ "level": "Air", "code": "10", "text": "四重溪流域" } ,
{ "level": "Air", "code": "11", "text": "立霧溪流域" } ,
{ "level": "Air", "code": "12", "text": "吉安溪流域" } ,
{ "level": "Air", "code": "13", "text": "朴子溪流域" } ,
{ "level": "Air", "code": "14", "text": "老街溪流域" } ,
{ "level": "Air", "code": "15", "text": "西湖溪流域" } ,
{ "level": "Air", "code": "16", "text": "利嘉溪流域" } ,
{ "level": "Air", "code": "17", "text": "秀姑巒溪流域" } ,
{ "level": "Air", "code": "18", "text": "卑南溪流域" } ,
{ "level": "Air", "code": "19", "text": "和平溪流域" } ,
{ "level": "Air", "code": "20", "text": "枋山溪流域" } ,
{ "level": "Air", "code": "21", "text": "東港溪流域" } ,
{ "level": "Air", "code": "22", "text": "林邊溪流域" } ,
{ "level": "Air", "code": "23", "text": "知本溪流域" } ,
{ "level": "Air", "code": "24", "text": "社子溪流域" } ,
{ "level": "Air", "code": "25", "text": "花蓮溪流域" } ,
{ "level": "Air", "code": "26", "text": "阿公店溪流域" } ,
{ "level": "Air", "code": "27", "text": "保力溪流域" } ,
{ "level": "Air", "code": "28", "text": "南崁溪流域" } ,
{ "level": "Air", "code": "29", "text": "南澳溪流域" } ,
{ "level": "Air", "code": "30", "text": "客雅溪流域" } ,
{ "level": "Air", "code": "31", "text": "後龍溪流域" } ,
{ "level": "Air", "code": "32", "text": "急水溪流域" } ,
{ "level": "Air", "code": "33", "text": "美崙溪流域" } ,
{ "level": "Air", "code": "34", "text": "烏溪流域" } ,
{ "level": "Air", "code": "35", "text": "高屏溪流域" } ,
{ "level": "Air", "code": "36", "text": "得子口溪流域" } ,
{ "level": "Air", "code": "37", "text": "淡水河流域" } ,
{ "level": "Air", "code": "38", "text": "率芒溪流域" } ,
{ "level": "Air", "code": "39", "text": "曾文溪流域" } ,
{ "level": "Air", "code": "40", "text": "港口溪流域" } ,
{ "level": "Air", "code": "41", "text": "新虎尾溪流域" } ,
{ "level": "Air", "code": "42", "text": "新城溪流域" } ,
{ "level": "Air", "code": "43", "text": "新豐溪流域" } ,
{ "level": "Air", "code": "44", "text": "楓港溪流域" } ,
{ "level": "Air", "code": "45", "text": "福興溪流域" } ,
{ "level": "Air", "code": "46", "text": "鳳山溪流域" } ,
{ "level": "Air", "code": "47", "text": "濁水溪流域" } ,
{ "level": "Air", "code": "48", "text": "頭前溪流域" } ,
{ "level": "Air", "code": "49", "text": "磺溪流域" } ,
{ "level": "Air", "code": "50", "text": "雙溪流域" } ,
{ "level": "Air", "code": "51", "text": "蘇澳溪流域" } ,
{ "level": "Air", "code": "52", "text": "蘭陽溪流域" } ,
{ "level": "Air", "code": "53", "text": "鹽水溪流域" } ,
{ "level": "Air", "code": "54", "text": "鹽港溪流域" } ,
{ "level": "City", "code": "66", "text": "臺中市", "AreaId": "4" } ,
{ "level": "City", "code": "66", "text": "臺中市", "AreaId": "5" } ,
{ "level": "City", "code": "66", "text": "臺中市", "AreaId": "34" } ,
{ "level": "City", "code": "63", "text": "臺北市", "AreaId": "37" } ,
{ "level": "City", "code": "10014", "text": "臺東縣", "AreaId": "7" } ,
{ "level": "City", "code": "10014", "text": "臺東縣", "AreaId": "16" } ,
{ "level": "City", "code": "10014", "text": "臺東縣", "AreaId": "18" } ,
{ "level": "City", "code": "10014", "text": "臺東縣", "AreaId": "23" } ,
{ "level": "City", "code": "67", "text": "臺南市", "AreaId": "1" } ,
{ "level": "City", "code": "67", "text": "臺南市", "AreaId": "2" } ,
{ "level": "City", "code": "67", "text": "臺南市", "AreaId": "32" } ,
{ "level": "City", "code": "67", "text": "臺南市", "AreaId": "39" } ,
{ "level": "City", "code": "67", "text": "臺南市", "AreaId": "53" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "8" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "19" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "29" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "36" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "42" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "51" } ,
{ "level": "City", "code": "10002", "text": "宜蘭縣", "AreaId": "52" } ,
{ "level": "City", "code": "10015", "text": "花蓮縣", "AreaId": "3" } ,
{ "level": "City", "code": "10015", "text": "花蓮縣", "AreaId": "11" } ,
{ "level": "City", "code": "10015", "text": "花蓮縣", "AreaId": "12" } ,
{ "level": "City", "code": "10015", "text": "花蓮縣", "AreaId": "17" } ,
{ "level": "City", "code": "10015", "text": "花蓮縣", "AreaId": "25" } ,
{ "level": "City", "code": "10015", "text": "花蓮縣", "AreaId": "33" } ,
{ "level": "City", "code": "10008", "text": "南投縣", "AreaId": "34" } ,
{ "level": "City", "code": "10008", "text": "南投縣", "AreaId": "47" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "10" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "20" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "21" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "22" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "27" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "35" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "38" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "40" } ,
{ "level": "City", "code": "10013", "text": "屏東縣", "AreaId": "44" } ,
{ "level": "City", "code": "10005", "text": "苗栗縣", "AreaId": "5" } ,
{ "level": "City", "code": "10005", "text": "苗栗縣", "AreaId": "6" } ,
{ "level": "City", "code": "10005", "text": "苗栗縣", "AreaId": "15" } ,
{ "level": "City", "code": "10005", "text": "苗栗縣", "AreaId": "31" } ,
{ "level": "City", "code": "68", "text": "桃園市", "AreaId": "14" } ,
{ "level": "City", "code": "68", "text": "桃園市", "AreaId": "24" } ,
{ "level": "City", "code": "68", "text": "桃園市", "AreaId": "28" } ,
{ "level": "City", "code": "68", "text": "桃園市", "AreaId": "37" } ,
{ "level": "City", "code": "68", "text": "桃園市", "AreaId": "45" } ,
{ "level": "City", "code": "64", "text": "高雄市", "AreaId": "1" } ,
{ "level": "City", "code": "64", "text": "高雄市", "AreaId": "26" } ,
{ "level": "City", "code": "64", "text": "高雄市", "AreaId": "35" } ,
{ "level": "City", "code": "10017", "text": "基隆市", "AreaId": "37" } ,
{ "level": "City", "code": "10009", "text": "雲林縣", "AreaId": "9" } ,
{ "level": "City", "code": "10009", "text": "雲林縣", "AreaId": "41" } ,
{ "level": "City", "code": "10009", "text": "雲林縣", "AreaId": "47" } ,
{ "level": "City", "code": "65", "text": "新北市", "AreaId": "37" } ,
{ "level": "City", "code": "65", "text": "新北市", "AreaId": "49" } ,
{ "level": "City", "code": "65", "text": "新北市", "AreaId": "50" } ,
{ "level": "City", "code": "10018", "text": "新竹市", "AreaId": "30" } ,
{ "level": "City", "code": "10018", "text": "新竹市", "AreaId": "48" } ,
{ "level": "City", "code": "10018", "text": "新竹市", "AreaId": "54" } ,
{ "level": "City", "code": "10004", "text": "新竹縣", "AreaId": "43" } ,
{ "level": "City", "code": "10004", "text": "新竹縣", "AreaId": "45" } ,
{ "level": "City", "code": "10004", "text": "新竹縣", "AreaId": "46" } ,
{ "level": "City", "code": "10004", "text": "新竹縣", "AreaId": "48" } ,
{ "level": "City", "code": "10004", "text": "新竹縣", "AreaId": "54" } ,
{ "level": "City", "code": "10020", "text": "嘉義市", "AreaId": "2" } ,
{ "level": "City", "code": "10020", "text": "嘉義市", "AreaId": "13" } ,
{ "level": "City", "code": "10010", "text": "嘉義縣", "AreaId": "2" } ,
{ "level": "City", "code": "10010", "text": "嘉義縣", "AreaId": "9" } ,
{ "level": "City", "code": "10010", "text": "嘉義縣", "AreaId": "13" } ,
{ "level": "City", "code": "10007", "text": "彰化縣", "AreaId": "34" } ,
{ "level": "Station", "code": "1", "text": "七結橋(取代得子口橋)", "create_date": "" } ,
{ "level": "Station", "code": "2", "text": "九如橋", "create_date": "" } ,
{ "level": "Station", "code": "3", "text": "二高便道橋", "create_date": "" } ,
{ "level": "Station", "code": "4", "text": "二港橋", "create_date": "" } ,
{ "level": "Station", "code": "5", "text": "二溪大橋", "create_date": "" } ,
{ "level": "Station", "code": "6", "text": "二層行橋", "create_date": "" } ,
{ "level": "Station", "code": "7", "text": "二層橋", "create_date": "" } ,
{ "level": "Station", "code": "8", "text": "八掌溪橋", "create_date": "" } ,
{ "level": "Station", "code": "9", "text": "三峽大橋", "create_date": "" } ,
{ "level": "Station", "code": "10", "text": "三峽河抽水站(取代醒心橋)", "create_date": "" } ,
{ "level": "Station", "code": "11", "text": "三棧橋", "create_date": "" } ,
{ "level": "Station", "code": "12", "text": "三聖橋", "create_date": "" } ,
{ "level": "Station", "code": "13", "text": "三鶯大橋", "create_date": "" } ,
{ "level": "Station", "code": "14", "text": "三灣大橋", "create_date": "" } ,
{ "level": "Station", "code": "15", "text": "上磺溪橋", "create_date": "" } ,
{ "level": "Station", "code": "16", "text": "下荖溪橋", "create_date": "" } ,
{ "level": "Station", "code": "17", "text": "千鳥橋", "create_date": "" } ,
{ "level": "Station", "code": "18", "text": "土庫大橋", "create_date": "" } ,
{ "level": "Station", "code": "19", "text": "大內橋（取代北勢洲橋）", "create_date": "" } ,
{ "level": "Station", "code": "20", "text": "大巴六九巴取水口", "create_date": "" } ,
{ "level": "Station", "code": "21", "text": "大甲溪橋", "create_date": "" } ,
{ "level": "Station", "code": "22", "text": "大安溪橋", "create_date": "" } ,
{ "level": "Station", "code": "23", "text": "大里橋", "create_date": "" } ,
{ "level": "Station", "code": "24", "text": "大直橋", "create_date": "" } ,
{ "level": "Station", "code": "25", "text": "大度橋(原為大肚橋)", "create_date": "" } ,
{ "level": "Station", "code": "26", "text": "大津橋", "create_date": "" } ,
{ "level": "Station", "code": "27", "text": "大埔橋", "create_date": "" } ,
{ "level": "Station", "code": "28", "text": "大溪橋", "create_date": "" } ,
{ "level": "Station", "code": "29", "text": "大濁水橋", "create_date": "" } ,
{ "level": "Station", "code": "30", "text": "大檜溪橋", "create_date": "" } ,
{ "level": "Station", "code": "31", "text": "山崎橋", "create_date": "" } ,
{ "level": "Station", "code": "32", "text": "中山橋", "create_date": "" } ,
{ "level": "Station", "code": "33", "text": "中山橋(新豐溪)", "create_date": "" } ,
{ "level": "Station", "code": "34", "text": "中正大橋", "create_date": "" } ,
{ "level": "Station", "code": "35", "text": "中正橋", "create_date": "" } ,
{ "level": "Station", "code": "36", "text": "中正橋", "create_date": "" } ,
{ "level": "Station", "code": "37", "text": "中正橋", "create_date": "" } ,
{ "level": "Station", "code": "38", "text": "中正橋", "create_date": "" } ,
{ "level": "Station", "code": "39", "text": "中正橋", "create_date": "" } ,
{ "level": "Station", "code": "40", "text": "中隘橋", "create_date": "" } ,
{ "level": "Station", "code": "41", "text": "五王大橋(原為南鯤鯓)", "create_date": "" } ,
{ "level": "Station", "code": "42", "text": "五空橋", "create_date": "" } ,
{ "level": "Station", "code": "43", "text": "五虎寮橋(取代舊橋)", "create_date": "" } ,
{ "level": "Station", "code": "44", "text": "仁里橋", "create_date": "" } ,
{ "level": "Station", "code": "45", "text": "介壽橋", "create_date": "" } ,
{ "level": "Station", "code": "46", "text": "介壽橋", "create_date": "" } ,
{ "level": "Station", "code": "47", "text": "內灣吊橋", "create_date": "" } ,
{ "level": "Station", "code": "48", "text": "公園橋上游(原為青埔橋)", "create_date": "" } ,
{ "level": "Station", "code": "49", "text": "六合橋", "create_date": "" } ,
{ "level": "Station", "code": "50", "text": "六龜大橋", "create_date": "" } ,
{ "level": "Station", "code": "51", "text": "太平溪橋", "create_date": "" } ,
{ "level": "Station", "code": "52", "text": "太平橋", "create_date": "" } ,
{ "level": "Station", "code": "53", "text": "太昌橋", "create_date": "" } ,
{ "level": "Station", "code": "54", "text": "巴士墨段橋(取代伊屯吊橋)", "create_date": "" } ,
{ "level": "Station", "code": "55", "text": "支亞干橋(取代豐平橋)", "create_date": "" } ,
{ "level": "Station", "code": "56", "text": "文峰橋", "create_date": "" } ,
{ "level": "Station", "code": "57", "text": "斗山橋", "create_date": "" } ,
{ "level": "Station", "code": "58", "text": "月眉潭橋", "create_date": "" } ,
{ "level": "Station", "code": "59", "text": "月眉橋", "create_date": "" } ,
{ "level": "Station", "code": "60", "text": "月眉橋", "create_date": "" } ,
{ "level": "Station", "code": "61", "text": "木瓜溪橋", "create_date": "" } ,
{ "level": "Station", "code": "62", "text": "水源橋上游", "create_date": "" } ,
{ "level": "Station", "code": "63", "text": "牛鬥橋", "create_date": "" } ,
{ "level": "Station", "code": "64", "text": "牛稠溪橋", "create_date": "" } ,
{ "level": "Station", "code": "65", "text": "冬山河橋", "create_date": "" } ,
{ "level": "Station", "code": "66", "text": "北山橋", "create_date": "" } ,
{ "level": "Station", "code": "67", "text": "北勢大橋", "create_date": "" } ,
{ "level": "Station", "code": "68", "text": "北勢橋", "create_date": "" } ,
{ "level": "Station", "code": "69", "text": "古亭橋", "create_date": "" } ,
{ "level": "Station", "code": "70", "text": "台15線鳳山溪橋", "create_date": "" } ,
{ "level": "Station", "code": "71", "text": "台19甲急水溪橋", "create_date": "" } ,
{ "level": "Station", "code": "72", "text": "台1線急水溪橋", "create_date": "" } ,
{ "level": "Station", "code": "73", "text": "台1線鳳山溪橋", "create_date": "" } ,
{ "level": "Station", "code": "74", "text": "台東大橋", "create_date": "" } ,
{ "level": "Station", "code": "75", "text": "四十號橋", "create_date": "" } ,
{ "level": "Station", "code": "76", "text": "平安大橋", "create_date": "" } ,
{ "level": "Station", "code": "77", "text": "平林橋", "create_date": "" } ,
{ "level": "Station", "code": "78", "text": "平鎮第一號橋", "create_date": "" } ,
{ "level": "Station", "code": "79", "text": "民權大橋", "create_date": "" } ,
{ "level": "Station", "code": "80", "text": "永寧一號橋", "create_date": "" } ,
{ "level": "Station", "code": "81", "text": "永寧橋", "create_date": "" } ,
{ "level": "Station", "code": "82", "text": "永樂里", "create_date": "" } ,
{ "level": "Station", "code": "83", "text": "永興橋", "create_date": "" } ,
{ "level": "Station", "code": "84", "text": "玉井橋", "create_date": "" } ,
{ "level": "Station", "code": "85", "text": "玉成橋(原為嘉里二號橋)", "create_date": "" } ,
{ "level": "Station", "code": "86", "text": "玉里大橋", "create_date": "" } ,
{ "level": "Station", "code": "87", "text": "玉峰大橋", "create_date": "" } ,
{ "level": "Station", "code": "88", "text": "玉峰大橋", "create_date": "" } ,
{ "level": "Station", "code": "89", "text": "甘宅二號橋(原為木屐寮)", "create_date": "" } ,
{ "level": "Station", "code": "90", "text": "甲仙取水口(取代四德大橋)", "create_date": "" } ,
{ "level": "Station", "code": "91", "text": "白布帆大橋", "create_date": "" } ,
{ "level": "Station", "code": "92", "text": "白米橋", "create_date": "" } ,
{ "level": "Station", "code": "93", "text": "石安橋", "create_date": "" } ,
{ "level": "Station", "code": "94", "text": "石門村過四重溪水泥橋(原為石門)", "create_date": "" } ,
{ "level": "Station", "code": "95", "text": "石榴班橋", "create_date": "" } ,
{ "level": "Station", "code": "96", "text": "同心橋", "create_date": "" } ,
{ "level": "Station", "code": "97", "text": "名竹大橋", "create_date": "" } ,
{ "level": "Station", "code": "98", "text": "后豐大橋", "create_date": "" } ,
{ "level": "Station", "code": "99", "text": "宅港橋", "create_date": "" } ,
{ "level": "Station", "code": "100", "text": "尖山大橋(取代中港溪橋)", "create_date": "" } ,
{ "level": "Station", "code": "101", "text": "成美橋", "create_date": "" } ,
{ "level": "Station", "code": "102", "text": "朴子口", "create_date": "" } ,
{ "level": "Station", "code": "103", "text": "朴子溪橋", "create_date": "" } ,
{ "level": "Station", "code": "104", "text": "江北橋", "create_date": "" } ,
{ "level": "Station", "code": "105", "text": "百齡橋", "create_date": "" } ,
{ "level": "Station", "code": "106", "text": "竹東大橋", "create_date": "" } ,
{ "level": "Station", "code": "107", "text": "竹林大橋", "create_date": "" } ,
{ "level": "Station", "code": "108", "text": "竹崎大橋", "create_date": "" } ,
{ "level": "Station", "code": "109", "text": "竹盛大橋", "create_date": "" } ,
{ "level": "Station", "code": "110", "text": "竹圍大橋", "create_date": "" } ,
{ "level": "Station", "code": "111", "text": "竹森大橋(原名銅鑼橋)", "create_date": "" } ,
{ "level": "Station", "code": "112", "text": "老飯店橋", "create_date": "" } ,
{ "level": "Station", "code": "113", "text": "西門大橋", "create_date": "" } ,
{ "level": "Station", "code": "114", "text": "西港大橋", "create_date": "" } ,
{ "level": "Station", "code": "115", "text": "西湖橋(原名四湖橋)", "create_date": "" } ,
{ "level": "Station", "code": "116", "text": "西濱快速道路(取代大安溪出海口)", "create_date": "" } ,
{ "level": "Station", "code": "117", "text": "西螺大橋", "create_date": "" } ,
{ "level": "Station", "code": "118", "text": "利民橋", "create_date": "" } ,
{ "level": "Station", "code": "119", "text": "利澤簡橋", "create_date": "" } ,
{ "level": "Station", "code": "120", "text": "宏太橋", "create_date": "" } ,
{ "level": "Station", "code": "121", "text": "秀朗橋", "create_date": "" } ,
{ "level": "Station", "code": "122", "text": "走馬瀨橋", "create_date": "" } ,
{ "level": "Station", "code": "123", "text": "里港大橋", "create_date": "" } ,
{ "level": "Station", "code": "124", "text": "里嶺大橋(取代嶺口橋)", "create_date": "" } ,
{ "level": "Station", "code": "125", "text": "初來橋", "create_date": "" } ,
{ "level": "Station", "code": "126", "text": "卓蘭大橋(原名為蘭勢橋)", "create_date": "" } ,
{ "level": "Station", "code": "127", "text": "協成橋", "create_date": "" } ,
{ "level": "Station", "code": "128", "text": "和平橋", "create_date": "" } ,
{ "level": "Station", "code": "129", "text": "忠孝大橋", "create_date": "" } ,
{ "level": "Station", "code": "130", "text": "昇高大橋(取代深坑中正橋)", "create_date": "" } ,
{ "level": "Station", "code": "131", "text": "昌農橋", "create_date": "" } ,
{ "level": "Station", "code": "132", "text": "東石大橋", "create_date": "" } ,
{ "level": "Station", "code": "133", "text": "東海橋", "create_date": "" } ,
{ "level": "Station", "code": "134", "text": "東港大橋", "create_date": "" } ,
{ "level": "Station", "code": "135", "text": "東勢大橋(原名東豐大橋)", "create_date": "" } ,
{ "level": "Station", "code": "136", "text": "東興大橋", "create_date": "" } ,
{ "level": "Station", "code": "137", "text": "東興橋", "create_date": "" } ,
{ "level": "Station", "code": "138", "text": "松竹大橋", "create_date": "" } ,
{ "level": "Station", "code": "139", "text": "松鶴橋(原為長青橋)", "create_date": "" } ,
{ "level": "Station", "code": "140", "text": "板新取水口", "create_date": "" } ,
{ "level": "Station", "code": "141", "text": "枋山大橋(原為枋山橋)", "create_date": "" } ,
{ "level": "Station", "code": "142", "text": "枋寮大橋", "create_date": "" } ,
{ "level": "Station", "code": "143", "text": "林邊大橋", "create_date": "" } ,
{ "level": "Station", "code": "144", "text": "武荖坑", "create_date": "" } ,
{ "level": "Station", "code": "145", "text": "直潭堰取水口", "create_date": "" } ,
{ "level": "Station", "code": "146", "text": "知本溫泉橋", "create_date": "" } ,
{ "level": "Station", "code": "147", "text": "知本橋", "create_date": "" } ,
{ "level": "Station", "code": "148", "text": "社子橋", "create_date": "" } ,
{ "level": "Station", "code": "149", "text": "花蓮大橋", "create_date": "" } ,
{ "level": "Station", "code": "150", "text": "迎賓橋", "create_date": "" } ,
{ "level": "Station", "code": "151", "text": "金洋二號橋(原為金洋)", "create_date": "" } ,
{ "level": "Station", "code": "152", "text": "長庚橋(取代石岡壩)", "create_date": "" } ,
{ "level": "Station", "code": "153", "text": "阿公店出水口", "create_date": "" } ,
{ "level": "Station", "code": "154", "text": "阿公店橋", "create_date": "" } ,
{ "level": "Station", "code": "155", "text": "青葉橋", "create_date": "" } ,
{ "level": "Station", "code": "156", "text": "青潭堰", "create_date": "" } ,
{ "level": "Station", "code": "157", "text": "侯硐車站", "create_date": "" } ,
{ "level": "Station", "code": "158", "text": "前州橋", "create_date": "" } ,
{ "level": "Station", "code": "159", "text": "南崁溪橋", "create_date": "" } ,
{ "level": "Station", "code": "160", "text": "南港溪橋", "create_date": "" } ,
{ "level": "Station", "code": "161", "text": "南湖大橋", "create_date": "" } ,
{ "level": "Station", "code": "162", "text": "南華大橋", "create_date": "" } ,
{ "level": "Station", "code": "163", "text": "南萣橋", "create_date": "" } ,
{ "level": "Station", "code": "164", "text": "南雄橋", "create_date": "" } ,
{ "level": "Station", "code": "165", "text": "南雲大橋", "create_date": "" } ,
{ "level": "Station", "code": "166", "text": "南澳橋", "create_date": "" } ,
{ "level": "Station", "code": "167", "text": "厚生橋", "create_date": "" } ,
{ "level": "Station", "code": "168", "text": "客雅溪橋", "create_date": "" } ,
{ "level": "Station", "code": "169", "text": "後池堰", "create_date": "" } ,
{ "level": "Station", "code": "170", "text": "後龍溪橋", "create_date": "" } ,
{ "level": "Station", "code": "171", "text": "星見橋", "create_date": "" } ,
{ "level": "Station", "code": "172", "text": "柑子林橋", "create_date": "" } ,
{ "level": "Station", "code": "173", "text": "柑園大橋(取代後村圳取水口)", "create_date": "" } ,
{ "level": "Station", "code": "174", "text": "紅樹林橋(原為紅毛港大橋)", "create_date": "" } ,
{ "level": "Station", "code": "175", "text": "美都麗橋", "create_date": "" } ,
{ "level": "Station", "code": "176", "text": "美慶山莊", "create_date": "" } ,
{ "level": "Station", "code": "177", "text": "茄苳溪橋", "create_date": "" } ,
{ "level": "Station", "code": "178", "text": "軍輝橋", "create_date": "" } ,
{ "level": "Station", "code": "179", "text": "重陽大橋", "create_date": "" } ,
{ "level": "Station", "code": "180", "text": "香雅橋", "create_date": "" } ,
{ "level": "Station", "code": "181", "text": "倡和橋", "create_date": "" } ,
{ "level": "Station", "code": "182", "text": "員笨橋", "create_date": "" } ,
{ "level": "Station", "code": "183", "text": "時潮橋(原為復興橋)", "create_date": "" } ,
{ "level": "Station", "code": "184", "text": "浮洲橋", "create_date": "" } ,
{ "level": "Station", "code": "185", "text": "海墘大橋", "create_date": "" } ,
{ "level": "Station", "code": "186", "text": "海豐橋", "create_date": "" } ,
{ "level": "Station", "code": "187", "text": "烏溪橋", "create_date": "" } ,
{ "level": "Station", "code": "188", "text": "貢寮大橋", "create_date": "" } ,
{ "level": "Station", "code": "189", "text": "馬蘭橋", "create_date": "" } ,
{ "level": "Station", "code": "190", "text": "高屏大橋", "create_date": "" } ,
{ "level": "Station", "code": "191", "text": "高速公路橋", "create_date": "" } ,
{ "level": "Station", "code": "192", "text": "高速鐵路橋下游便橋", "create_date": "" } ,
{ "level": "Station", "code": "193", "text": "乾峰橋", "create_date": "" } ,
{ "level": "Station", "code": "194", "text": "國光橋", "create_date": "" } ,
{ "level": "Station", "code": "195", "text": "國姓橋(原為國聖橋)", "create_date": "" } ,
{ "level": "Station", "code": "196", "text": "崇德橋", "create_date": "" } ,
{ "level": "Station", "code": "197", "text": "崙埤橋(原為崙碑)", "create_date": "" } ,
{ "level": "Station", "code": "198", "text": "梅林橋", "create_date": "" } ,
{ "level": "Station", "code": "199", "text": "梅南橋", "create_date": "" } ,
{ "level": "Station", "code": "200", "text": "淡水河口", "create_date": "" } ,
{ "level": "Station", "code": "201", "text": "深坑橋", "create_date": "" } ,
{ "level": "Station", "code": "202", "text": "清水大閘", "create_date": "" } ,
{ "level": "Station", "code": "203", "text": "清流橋", "create_date": "" } ,
{ "level": "Station", "code": "204", "text": "笨子港橋", "create_date": "" } ,
{ "level": "Station", "code": "205", "text": "許厝港一號橋", "create_date": "" } ,
{ "level": "Station", "code": "206", "text": "逢甲橋", "create_date": "" } ,
{ "level": "Station", "code": "207", "text": "鹿鳴橋", "create_date": "" } ,
{ "level": "Station", "code": "208", "text": "麻善大橋", "create_date": "" } ,
{ "level": "Station", "code": "209", "text": "普渡大橋", "create_date": "" } ,
{ "level": "Station", "code": "210", "text": "曾文一橋(原為曾文一號橋)", "create_date": "" } ,
{ "level": "Station", "code": "211", "text": "曾文溪河口", "create_date": "" } ,
{ "level": "Station", "code": "212", "text": "曾文溪橋", "create_date": "" } ,
{ "level": "Station", "code": "213", "text": "渡船大橋", "create_date": "" } ,
{ "level": "Station", "code": "214", "text": "港口橋", "create_date": "" } ,
{ "level": "Station", "code": "215", "text": "港西抽水站", "create_date": "" } ,
{ "level": "Station", "code": "216", "text": "湳雅取水口(取代溪洲大橋)", "create_date": "" } ,
{ "level": "Station", "code": "217", "text": "莿桐一號橋", "create_date": "" } ,
{ "level": "Station", "code": "218", "text": "華中大橋", "create_date": "" } ,
{ "level": "Station", "code": "219", "text": "華江大橋", "create_date": "" } ,
{ "level": "Station", "code": "220", "text": "象鼻橋", "create_date": "" } ,
{ "level": "Station", "code": "221", "text": "貂嶺車站", "create_date": "" } ,
{ "level": "Station", "code": "222", "text": "集泉橋", "create_date": "" } ,
{ "level": "Station", "code": "223", "text": "集鹿大橋", "create_date": "" } ,
{ "level": "Station", "code": "224", "text": "雲嘉大橋", "create_date": "" } ,
{ "level": "Station", "code": "225", "text": "愛蘭橋", "create_date": "" } ,
{ "level": "Station", "code": "226", "text": "新生橋", "create_date": "" } ,
{ "level": "Station", "code": "227", "text": "新生橋(原為嘉新村)", "create_date": "" } ,
{ "level": "Station", "code": "228", "text": "新虎尾溪橋", "create_date": "" } ,
{ "level": "Station", "code": "229", "text": "新城橋", "create_date": "" } ,
{ "level": "Station", "code": "230", "text": "新城橋", "create_date": "" } ,
{ "level": "Station", "code": "231", "text": "新埔大橋", "create_date": "" } ,
{ "level": "Station", "code": "232", "text": "新海大橋", "create_date": "" } ,
{ "level": "Station", "code": "233", "text": "新埤大橋", "create_date": "" } ,
{ "level": "Station", "code": "234", "text": "新湖橋", "create_date": "" } ,
{ "level": "Station", "code": "235", "text": "新發大橋", "create_date": "" } ,
{ "level": "Station", "code": "236", "text": "新園橋(原為大南橋)", "create_date": "" } ,
{ "level": "Station", "code": "237", "text": "新旗尾橋", "create_date": "" } ,
{ "level": "Station", "code": "238", "text": "新寮大橋", "create_date": "" } ,
{ "level": "Station", "code": "239", "text": "新寮橋(原為新寮吊橋)", "create_date": "" } ,
{ "level": "Station", "code": "240", "text": "新灣橋", "create_date": "" } ,
{ "level": "Station", "code": "241", "text": "暖江橋", "create_date": "" } ,
{ "level": "Station", "code": "242", "text": "楓林橋", "create_date": "" } ,
{ "level": "Station", "code": "243", "text": "楓港溪橋", "create_date": "" } ,
{ "level": "Station", "code": "244", "text": "溪南橋", "create_date": "" } ,
{ "level": "Station", "code": "245", "text": "瑞昌大橋(原為瑞豐大橋)", "create_date": "" } ,
{ "level": "Station", "code": "246", "text": "瑞穗大橋", "create_date": "" } ,
{ "level": "Station", "code": "247", "text": "義里大橋", "create_date": "" } ,
{ "level": "Station", "code": "248", "text": "萬大大橋", "create_date": "" } ,
{ "level": "Station", "code": "249", "text": "萬里溪橋", "create_date": "" } ,
{ "level": "Station", "code": "250", "text": "萬壽橋", "create_date": "" } ,
{ "level": "Station", "code": "251", "text": "葫蘆堵大橋(原為上深溝)", "create_date": "" } ,
{ "level": "Station", "code": "252", "text": "誠仁橋", "create_date": "" } ,
{ "level": "Station", "code": "253", "text": "隘寮堰", "create_date": "" } ,
{ "level": "Station", "code": "254", "text": "嘉南大橋", "create_date": "" } ,
{ "level": "Station", "code": "255", "text": "實踐橋", "create_date": "" } ,
{ "level": "Station", "code": "256", "text": "旗南橋", "create_date": "" } ,
{ "level": "Station", "code": "257", "text": "榮橋", "create_date": "" } ,
{ "level": "Station", "code": "258", "text": "碧潭吊橋(取代碧潭大橋)", "create_date": "" } ,
{ "level": "Station", "code": "259", "text": "福馬圳", "create_date": "" } ,
{ "level": "Station", "code": "260", "text": "網寮橋(原為建國村)", "create_date": "" } ,
{ "level": "Station", "code": "261", "text": "鳳凰橋(原為青草湖)", "create_date": "" } ,
{ "level": "Station", "code": "262", "text": "廣興橋(取代屈尺堰)", "create_date": "" } ,
{ "level": "Station", "code": "263", "text": "潮州大橋", "create_date": "" } ,
{ "level": "Station", "code": "264", "text": "蓬萊橋(原為阿公店溪)", "create_date": "" } ,
{ "level": "Station", "code": "265", "text": "噶瑪蘭橋(原為興蘭大橋)", "create_date": "" } ,
{ "level": "Station", "code": "266", "text": "樹王橋", "create_date": "" } ,
{ "level": "Station", "code": "267", "text": "澳尾橋", "create_date": "" } ,
{ "level": "Station", "code": "268", "text": "興社大橋", "create_date": "" } ,
{ "level": "Station", "code": "269", "text": "錦文橋", "create_date": "" } ,
{ "level": "Station", "code": "270", "text": "頭前溪橋", "create_date": "" } ,
{ "level": "Station", "code": "271", "text": "頭屋大橋", "create_date": "" } ,
{ "level": "Station", "code": "272", "text": "龍安橋", "create_date": "" } ,
{ "level": "Station", "code": "273", "text": "龍壽橋", "create_date": "" } ,
{ "level": "Station", "code": "274", "text": "龍德大橋", "create_date": "" } ,
{ "level": "Station", "code": "275", "text": "龍潭橋(原為龍鑾潭)", "create_date": "" } ,
{ "level": "Station", "code": "276", "text": "龜山橋", "create_date": "" } ,
{ "level": "Station", "code": "277", "text": "龜山橋", "create_date": "" } ,
{ "level": "Station", "code": "278", "text": "環鄉橋(原為宋屋)", "create_date": "" } ,
{ "level": "Station", "code": "279", "text": "磺溪橋", "create_date": "" } ,
{ "level": "Station", "code": "280", "text": "臨海橋", "create_date": "" } ,
{ "level": "Station", "code": "281", "text": "舊港橋", "create_date": "" } ,
{ "level": "Station", "code": "282", "text": "舊路大橋", "create_date": "" } ,
{ "level": "Station", "code": "283", "text": "豐化橋", "create_date": "" } ,
{ "level": "Station", "code": "284", "text": "豐里橋", "create_date": "" } ,
{ "level": "Station", "code": "285", "text": "豐源大橋", "create_date": "" } ,
{ "level": "Station", "code": "286", "text": "豐橋", "create_date": "" } ,
{ "level": "Station", "code": "287", "text": "雙園大橋", "create_date": "" } ,
{ "level": "Station", "code": "288", "text": "懷恩橋(原為二重溪)", "create_date": "" } ,
{ "level": "Station", "code": "289", "text": "關渡大橋", "create_date": "" } ,
{ "level": "Station", "code": "290", "text": "隴東橋(原為龍東橋)", "create_date": "" } ,
{ "level": "Station", "code": "291", "text": "寶山水庫取水口", "create_date": "" } ,
{ "level": "Station", "code": "292", "text": "寶橋", "create_date": "" } ,
{ "level": "Station", "code": "293", "text": "觸口橋", "create_date": "" } ,
{ "level": "Station", "code": "294", "text": "蘭陽大橋", "create_date": "" } ,
{ "level": "Station", "code": "295", "text": "鹽水溪橋", "create_date": "" } ,
{ "level": "Station", "code": "296", "text": "觀光大橋(取代北港大橋)", "create_date": "" } 
];
var map_basin_value = [ 
{ "code": "1", "value": 0, "drilldown": "1" },
{ "code": "2", "value": 0, "drilldown": "2" },
{ "code": "3", "value": 0, "drilldown": "3" },
{ "code": "4", "value": 0, "drilldown": "4" },
{ "code": "5", "value": 0, "drilldown": "5" },
{ "code": "6", "value": 0, "drilldown": "6" },
{ "code": "7", "value": 0, "drilldown": "7" },
{ "code": "8", "value": 0, "drilldown": "8" },
{ "code": "9", "value": 0, "drilldown": "9" },
{ "code": "10", "value": 0, "drilldown": "10" },
{ "code": "11", "value": 0, "drilldown": "11" },
{ "code": "12", "value": 0, "drilldown": "12" },
{ "code": "13", "value": 0, "drilldown": "13" },
{ "code": "14", "value": 0, "drilldown": "14" },
{ "code": "15", "value": 0, "drilldown": "15" },
{ "code": "16", "value": 0, "drilldown": "16" },
{ "code": "17", "value": 0, "drilldown": "17" },
{ "code": "18", "value": 0, "drilldown": "18" },
{ "code": "19", "value": 0, "drilldown": "19" },
{ "code": "20", "value": 0, "drilldown": "20" },
{ "code": "21", "value": 0, "drilldown": "21" },
{ "code": "22", "value": 0, "drilldown": "22" },
{ "code": "23", "value": 0, "drilldown": "23" },
{ "code": "24", "value": 0, "drilldown": "24" },
{ "code": "25", "value": 0, "drilldown": "25" },
{ "code": "26", "value": 0, "drilldown": "26" },
{ "code": "27", "value": 0, "drilldown": "27" },
{ "code": "28", "value": 0, "drilldown": "28" },
{ "code": "29", "value": 0, "drilldown": "29" },
{ "code": "30", "value": 0, "drilldown": "30" },
{ "code": "31", "value": 0, "drilldown": "31" },
{ "code": "32", "value": 0, "drilldown": "32" },
{ "code": "33", "value": 0, "drilldown": "33" },
{ "code": "34", "value": 0, "drilldown": "34" },
{ "code": "35", "value": 0, "drilldown": "35" },
{ "code": "36", "value": 0, "drilldown": "36" },
{ "code": "37", "value": 0, "drilldown": "37" },
{ "code": "38", "value": 0, "drilldown": "38" },
{ "code": "39", "value": 0, "drilldown": "39" },
{ "code": "40", "value": 0, "drilldown": "40" },
{ "code": "41", "value": 0, "drilldown": "41" },
{ "code": "42", "value": 0, "drilldown": "42" },
{ "code": "43", "value": 0, "drilldown": "43" },
{ "code": "44", "value": 0, "drilldown": "44" },
{ "code": "45", "value": 0, "drilldown": "45" },
{ "code": "46", "value": 0, "drilldown": "46" },
{ "code": "47", "value": 0, "drilldown": "47" },
{ "code": "48", "value": 0, "drilldown": "48" },
{ "code": "49", "value": 0, "drilldown": "49" },
{ "code": "50", "value": 0, "drilldown": "50" },
{ "code": "51", "value": 0, "drilldown": "51" },
{ "code": "52", "value": 0, "drilldown": "52" },
{ "code": "53", "value": 0, "drilldown": "53" },
{ "code": "54", "value": 0, "drilldown": "54" } ];
