'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection

Namespace WhitePaper
	
	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Danny_Test")>  _
	Partial Public Class DataClassesDataContext
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
		
    #Region "擴充性方法定義"
    Partial Private Sub OnCreated()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("Danny_TestConnectionString").ConnectionString, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public ReadOnly Property COemission() As System.Data.Linq.Table(Of WhitePaper.Table.COemission)
			Get
				Return Me.GetTable(Of WhitePaper.Table.COemission)
			End Get
		End Property
		
		Public ReadOnly Property AirQualityMonth() As System.Data.Linq.Table(Of WhitePaper.Table.AirQualityMonth)
			Get
				Return Me.GetTable(Of WhitePaper.Table.AirQualityMonth)
			End Get
		End Property
		
		Public ReadOnly Property AirStation() As System.Data.Linq.Table(Of WhitePaper.Table.AirStation)
			Get
				Return Me.GetTable(Of WhitePaper.Table.AirStation)
			End Get
		End Property
		
		Public ReadOnly Property data_pb() As System.Data.Linq.Table(Of WhitePaper.Table.data_pb)
			Get
				Return Me.GetTable(Of WhitePaper.Table.data_pb)
			End Get
		End Property
	End Class
End Namespace

Namespace WhitePaper.Table
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.COemission")>  _
	Partial Public Class COemission
		
		Private _TYPE As String
		
		Private __1993Y As System.Nullable(Of Double)
		
		Private __1994Y As System.Nullable(Of Double)
		
		Private __1995Y As System.Nullable(Of Double)
		
		Private __1996Y As System.Nullable(Of Double)
		
		Private __1997Y As System.Nullable(Of Double)
		
		Private __1998Y As System.Nullable(Of Double)
		
		Private __1999Y As System.Nullable(Of Double)
		
		Private __2000Y As System.Nullable(Of Double)
		
		Private __2001Y As System.Nullable(Of Double)
		
		Private __2002Y As System.Nullable(Of Double)
		
		Private __2003Y As System.Nullable(Of Double)
		
		Private __2004Y As System.Nullable(Of Double)
		
		Private __2005Y As System.Nullable(Of Double)
		
		Private __2006Y As System.Nullable(Of Double)
		
		Private __2007Y As System.Nullable(Of Double)
		
		Private __2008Y As System.Nullable(Of Double)
		
		Private __2009Y As System.Nullable(Of Double)
		
		Private __2010Y As System.Nullable(Of Double)
		
		Private __2011Y As System.Nullable(Of Double)
		
		Private __2012Y As System.Nullable(Of Double)
		
		Private __2013Y As System.Nullable(Of Double)
		
		Private __2014Y As System.Nullable(Of Double)
		
		Private __2015Y As System.Nullable(Of Double)
		
		Public Sub New()
			MyBase.New
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TYPE", DbType:="NVarChar(255)")>  _
		Public Property TYPE() As String
			Get
				Return Me._TYPE
			End Get
			Set
				If (String.Equals(Me._TYPE, value) = false) Then
					Me._TYPE = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1993Y]", Storage:="__1993Y", DbType:="Float")>  _
		Public Property _1993Y() As System.Nullable(Of Double)
			Get
				Return Me.__1993Y
			End Get
			Set
				If (Me.__1993Y.Equals(value) = false) Then
					Me.__1993Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1994Y]", Storage:="__1994Y", DbType:="Float")>  _
		Public Property _1994Y() As System.Nullable(Of Double)
			Get
				Return Me.__1994Y
			End Get
			Set
				If (Me.__1994Y.Equals(value) = false) Then
					Me.__1994Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1995Y]", Storage:="__1995Y", DbType:="Float")>  _
		Public Property _1995Y() As System.Nullable(Of Double)
			Get
				Return Me.__1995Y
			End Get
			Set
				If (Me.__1995Y.Equals(value) = false) Then
					Me.__1995Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1996Y]", Storage:="__1996Y", DbType:="Float")>  _
		Public Property _1996Y() As System.Nullable(Of Double)
			Get
				Return Me.__1996Y
			End Get
			Set
				If (Me.__1996Y.Equals(value) = false) Then
					Me.__1996Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1997Y]", Storage:="__1997Y", DbType:="Float")>  _
		Public Property _1997Y() As System.Nullable(Of Double)
			Get
				Return Me.__1997Y
			End Get
			Set
				If (Me.__1997Y.Equals(value) = false) Then
					Me.__1997Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1998Y]", Storage:="__1998Y", DbType:="Float")>  _
		Public Property _1998Y() As System.Nullable(Of Double)
			Get
				Return Me.__1998Y
			End Get
			Set
				If (Me.__1998Y.Equals(value) = false) Then
					Me.__1998Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[1999Y]", Storage:="__1999Y", DbType:="Float")>  _
		Public Property _1999Y() As System.Nullable(Of Double)
			Get
				Return Me.__1999Y
			End Get
			Set
				If (Me.__1999Y.Equals(value) = false) Then
					Me.__1999Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2000Y]", Storage:="__2000Y", DbType:="Float")>  _
		Public Property _2000Y() As System.Nullable(Of Double)
			Get
				Return Me.__2000Y
			End Get
			Set
				If (Me.__2000Y.Equals(value) = false) Then
					Me.__2000Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2001Y]", Storage:="__2001Y", DbType:="Float")>  _
		Public Property _2001Y() As System.Nullable(Of Double)
			Get
				Return Me.__2001Y
			End Get
			Set
				If (Me.__2001Y.Equals(value) = false) Then
					Me.__2001Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2002Y]", Storage:="__2002Y", DbType:="Float")>  _
		Public Property _2002Y() As System.Nullable(Of Double)
			Get
				Return Me.__2002Y
			End Get
			Set
				If (Me.__2002Y.Equals(value) = false) Then
					Me.__2002Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2003Y]", Storage:="__2003Y", DbType:="Float")>  _
		Public Property _2003Y() As System.Nullable(Of Double)
			Get
				Return Me.__2003Y
			End Get
			Set
				If (Me.__2003Y.Equals(value) = false) Then
					Me.__2003Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2004Y]", Storage:="__2004Y", DbType:="Float")>  _
		Public Property _2004Y() As System.Nullable(Of Double)
			Get
				Return Me.__2004Y
			End Get
			Set
				If (Me.__2004Y.Equals(value) = false) Then
					Me.__2004Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2005Y]", Storage:="__2005Y", DbType:="Float")>  _
		Public Property _2005Y() As System.Nullable(Of Double)
			Get
				Return Me.__2005Y
			End Get
			Set
				If (Me.__2005Y.Equals(value) = false) Then
					Me.__2005Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2006Y]", Storage:="__2006Y", DbType:="Float")>  _
		Public Property _2006Y() As System.Nullable(Of Double)
			Get
				Return Me.__2006Y
			End Get
			Set
				If (Me.__2006Y.Equals(value) = false) Then
					Me.__2006Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2007Y]", Storage:="__2007Y", DbType:="Float")>  _
		Public Property _2007Y() As System.Nullable(Of Double)
			Get
				Return Me.__2007Y
			End Get
			Set
				If (Me.__2007Y.Equals(value) = false) Then
					Me.__2007Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2008Y]", Storage:="__2008Y", DbType:="Float")>  _
		Public Property _2008Y() As System.Nullable(Of Double)
			Get
				Return Me.__2008Y
			End Get
			Set
				If (Me.__2008Y.Equals(value) = false) Then
					Me.__2008Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2009Y]", Storage:="__2009Y", DbType:="Float")>  _
		Public Property _2009Y() As System.Nullable(Of Double)
			Get
				Return Me.__2009Y
			End Get
			Set
				If (Me.__2009Y.Equals(value) = false) Then
					Me.__2009Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2010Y]", Storage:="__2010Y", DbType:="Float")>  _
		Public Property _2010Y() As System.Nullable(Of Double)
			Get
				Return Me.__2010Y
			End Get
			Set
				If (Me.__2010Y.Equals(value) = false) Then
					Me.__2010Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2011Y]", Storage:="__2011Y", DbType:="Float")>  _
		Public Property _2011Y() As System.Nullable(Of Double)
			Get
				Return Me.__2011Y
			End Get
			Set
				If (Me.__2011Y.Equals(value) = false) Then
					Me.__2011Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2012Y]", Storage:="__2012Y", DbType:="Float")>  _
		Public Property _2012Y() As System.Nullable(Of Double)
			Get
				Return Me.__2012Y
			End Get
			Set
				If (Me.__2012Y.Equals(value) = false) Then
					Me.__2012Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2013Y]", Storage:="__2013Y", DbType:="Float")>  _
		Public Property _2013Y() As System.Nullable(Of Double)
			Get
				Return Me.__2013Y
			End Get
			Set
				If (Me.__2013Y.Equals(value) = false) Then
					Me.__2013Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2014Y]", Storage:="__2014Y", DbType:="Float")>  _
		Public Property _2014Y() As System.Nullable(Of Double)
			Get
				Return Me.__2014Y
			End Get
			Set
				If (Me.__2014Y.Equals(value) = false) Then
					Me.__2014Y = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[2015Y]", Storage:="__2015Y", DbType:="Float")>  _
		Public Property _2015Y() As System.Nullable(Of Double)
			Get
				Return Me.__2015Y
			End Get
			Set
				If (Me.__2015Y.Equals(value) = false) Then
					Me.__2015Y = value
				End If
			End Set
		End Property
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.AirQualityMonth")>  _
	Partial Public Class AirQualityMonth
		
		Private _COUNTY As String
		
		Private _SITENAME As String
		
		Private _ITEMNAME As String
		
		Private _MONITORYEAR As String
		
		Private _MONITORMONTH As String
		
		Private _MONTHLYVALUE As System.Nullable(Of Double)
		
		Private _ITEMUNIT As String
		
		Public Sub New()
			MyBase.New
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COUNTY", DbType:="VarChar(50)")>  _
		Public Property COUNTY() As String
			Get
				Return Me._COUNTY
			End Get
			Set
				If (String.Equals(Me._COUNTY, value) = false) Then
					Me._COUNTY = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SITENAME", DbType:="VarChar(50)")>  _
		Public Property SITENAME() As String
			Get
				Return Me._SITENAME
			End Get
			Set
				If (String.Equals(Me._SITENAME, value) = false) Then
					Me._SITENAME = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEMNAME", DbType:="VarChar(50)")>  _
		Public Property ITEMNAME() As String
			Get
				Return Me._ITEMNAME
			End Get
			Set
				If (String.Equals(Me._ITEMNAME, value) = false) Then
					Me._ITEMNAME = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONITORYEAR", DbType:="VarChar(50)")>  _
		Public Property MONITORYEAR() As String
			Get
				Return Me._MONITORYEAR
			End Get
			Set
				If (String.Equals(Me._MONITORYEAR, value) = false) Then
					Me._MONITORYEAR = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONITORMONTH", DbType:="VarChar(50)")>  _
		Public Property MONITORMONTH() As String
			Get
				Return Me._MONITORMONTH
			End Get
			Set
				If (String.Equals(Me._MONITORMONTH, value) = false) Then
					Me._MONITORMONTH = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONTHLYVALUE", DbType:="Float")>  _
		Public Property MONTHLYVALUE() As System.Nullable(Of Double)
			Get
				Return Me._MONTHLYVALUE
			End Get
			Set
				If (Me._MONTHLYVALUE.Equals(value) = false) Then
					Me._MONTHLYVALUE = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITEMUNIT", DbType:="VarChar(50)")>  _
		Public Property ITEMUNIT() As String
			Get
				Return Me._ITEMUNIT
			End Get
			Set
				If (String.Equals(Me._ITEMUNIT, value) = false) Then
					Me._ITEMUNIT = value
				End If
			End Set
		End Property
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.AirStation")>  _
	Partial Public Class AirStation
		
		Private _NUMBER As System.Nullable(Of Double)
		
		Private _COUNTY As String
		
		Private _VILLAGE As String
		
		Private _SITENAME As String
		
		Private _SITETYPE As String
		
		Private _SITEADD As String
		
		Private _AIRQUALITYAREA As String
		
		Private _X As System.Nullable(Of Double)
		
		Private _Y As System.Nullable(Of Double)
		
		Public Sub New()
			MyBase.New
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NUMBER", DbType:="Float")>  _
		Public Property NUMBER() As System.Nullable(Of Double)
			Get
				Return Me._NUMBER
			End Get
			Set
				If (Me._NUMBER.Equals(value) = false) Then
					Me._NUMBER = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COUNTY", DbType:="NVarChar(255)")>  _
		Public Property COUNTY() As String
			Get
				Return Me._COUNTY
			End Get
			Set
				If (String.Equals(Me._COUNTY, value) = false) Then
					Me._COUNTY = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VILLAGE", DbType:="NVarChar(255)")>  _
		Public Property VILLAGE() As String
			Get
				Return Me._VILLAGE
			End Get
			Set
				If (String.Equals(Me._VILLAGE, value) = false) Then
					Me._VILLAGE = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SITENAME", DbType:="NVarChar(255)")>  _
		Public Property SITENAME() As String
			Get
				Return Me._SITENAME
			End Get
			Set
				If (String.Equals(Me._SITENAME, value) = false) Then
					Me._SITENAME = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SITETYPE", DbType:="NVarChar(255)")>  _
		Public Property SITETYPE() As String
			Get
				Return Me._SITETYPE
			End Get
			Set
				If (String.Equals(Me._SITETYPE, value) = false) Then
					Me._SITETYPE = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SITEADD", DbType:="NVarChar(255)")>  _
		Public Property SITEADD() As String
			Get
				Return Me._SITEADD
			End Get
			Set
				If (String.Equals(Me._SITEADD, value) = false) Then
					Me._SITEADD = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AIRQUALITYAREA", DbType:="NVarChar(255)")>  _
		Public Property AIRQUALITYAREA() As String
			Get
				Return Me._AIRQUALITYAREA
			End Get
			Set
				If (String.Equals(Me._AIRQUALITYAREA, value) = false) Then
					Me._AIRQUALITYAREA = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_X", DbType:="Float")>  _
		Public Property X() As System.Nullable(Of Double)
			Get
				Return Me._X
			End Get
			Set
				If (Me._X.Equals(value) = false) Then
					Me._X = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Y", DbType:="Float")>  _
		Public Property Y() As System.Nullable(Of Double)
			Get
				Return Me._Y
			End Get
			Set
				If (Me._Y.Equals(value) = false) Then
					Me._Y = value
				End If
			End Set
		End Property
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.data_pb")>  _
	Partial Public Class data_pb
		
		Private _id As Integer
		
		Private _city As String
		
		Private _d_year As System.Nullable(Of Integer)
		
		Private _d_month As System.Nullable(Of Integer)
		
		Private _d_value As System.Nullable(Of Double)
		
		Public Sub New()
			MyBase.New
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
		Public Property id() As Integer
			Get
				Return Me._id
			End Get
			Set
				If ((Me._id = value)  _
							= false) Then
					Me._id = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_city", DbType:="NVarChar(50)")>  _
		Public Property city() As String
			Get
				Return Me._city
			End Get
			Set
				If (String.Equals(Me._city, value) = false) Then
					Me._city = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_d_year", DbType:="Int")>  _
		Public Property d_year() As System.Nullable(Of Integer)
			Get
				Return Me._d_year
			End Get
			Set
				If (Me._d_year.Equals(value) = false) Then
					Me._d_year = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_d_month", DbType:="Int")>  _
		Public Property d_month() As System.Nullable(Of Integer)
			Get
				Return Me._d_month
			End Get
			Set
				If (Me._d_month.Equals(value) = false) Then
					Me._d_month = value
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_d_value", DbType:="Float")>  _
		Public Property d_value() As System.Nullable(Of Double)
			Get
				Return Me._d_value
			End Get
			Set
				If (Me._d_value.Equals(value) = false) Then
					Me._d_value = value
				End If
			End Set
		End Property
	End Class
End Namespace
